FROM ubuntu:22.04

RUN apt update && apt install -y \
    git=1:2.34.1-1ubuntu1.8 \
    python3=3.10.6-1~22.04 \
    python3-pip=22.0.2+dfsg-1ubuntu0.2 \
    pwgen=2.08-2build1 \
    openssh-server=1:8.9p1-3ubuntu0.1

RUN mkdir /var/run/sshd
RUN sed -i '/PermitRootLogin prohibit-password/c\PermitRootLogin yes' /etc/ssh/sshd_config

ADD requirements.txt .
RUN pip3 install -r requirements.txt

RUN git clone https://github.com/moevm/devops-examples.git
WORKDIR devops-examples/EXAMPLE_APP/

ADD add_host.patch start_sshd.sh ./
RUN patch main.py add_host.patch

ENTRYPOINT ["python3", "main.py"]
