version: "3"
services:
    app:
        env_file:
            - .env
        ports:
            -   "5000:5000"
            -   "5022:22"
        build: 
            dockerfile: Dockerfile_app
        deploy:
            resources:
                limits:
                    pids: 12
            
    tester:
        build: 
            dockerfile: Dockerfile_tester
